---
- name: Build target
  make:
    chdir: /tmp/zbx_systemd_module/zabbix-module-systemd-1.2.0
    target: install
    params:
      prefix: /usr
      sysconfdir: /etc
      libdir: /usr/lib64
  become: true
  notify:
    - restart zabbix-agent
