---
- name: Create target tmp dir
  file:
    path: /tmp/zbx_systemd_module
    state: directory

- name: Unarchive Zabbix SystemD Module
  unarchive:
    src: http://s3.cavaliercoder.com/zabbix-contrib/release/zabbix-module-systemd-1.2.0.tar.gz
    dest: /tmp/zbx_systemd_module/
    remote_src: yes

- name: Grab Zabbix Source
  subversion:
    repo: svn://svn.zabbix.com/tags/3.0.27 /usr/src/zabbix
    dest: /usr/src/zabbix
    export: yes
