---
- name: Unarchive Zabbix SystemD Module
  unarchive:
    src: http://s3.cavaliercoder.com/zabbix-contrib/release/zabbix-module-systemd-1.2.0.tar.gz
    dest: /tmp/zbx_systemd_module/

- name: Grab Zabbix Source
  git:
    repo: https://github.com/zabbix/zabbix.git
    dest: /usr/src/zabbix
    version: release/4.0
    export: yes
